# action.yml
name: "Hello World"
description: "Greet someone and record the time"
inputs:
  testinput: # id of input
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  my-output: # id of output
    description: "The time we greeted you"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.testinput }}
